// import {removeHyphensAndCapitalize, filterIconsByKeyword, excludeItemsByKeywords, random_tailwind_color, random_hex_color_code } from './helpers';
export { removeHyphensAndCapitalize, filterIconsByKeyword, excludeItemsByKeywords, random_tailwind_color, random_hex_color_code } from './helpers';

export { default as DynamicCodeBlockStyle } from './DynamicCodeBlockStyle.svelte';
export { default as Footer } from './Footer.svelte';
export { default as HomeCards } from './HomeCards.svelte';
export { default as IconPage } from './IconPage.svelte';
export { default as MetaTag } from './MetaTag.svelte';
export { default as Nav } from './Nav.svelte';
export { default as SupportBanner } from './SupportBanner.svelte';
export { default as TechInfo } from './TechInfo.svelte';

// icons
export { default as A7Solid } from './icons/A7Solid.svelte';
export { default as Accessibility } from './icons/Accessibility.svelte';
export { default as BadgeCheckOutline } from './icons/BadgeCheckOutline.svelte';
export { default as BellActiveAltOutline } from './icons/BellActiveAltOutline.svelte';
export { default as ChartLineUpOutline } from './icons/ChartLineUpOutline.svelte';
export { default as ChartPieOutline } from './icons/ChartPieOutline.svelte';
export { default as CheckCircleOutline } from './icons/CheckCircleOutline.svelte';
export { default as ChevronDownSolid } from './icons/ChevronDownSolid.svelte';
export { default as ChevronUpSolid } from './icons/ChevronUpSolid.svelte';
export { default as ClipboardListOutline } from './icons/ClipboardListOutline.svelte';
export { default as CodeOutline } from './icons/CodeOutline.svelte';
export { default as CogOutline } from './icons/CogOutline.svelte';
export { default as DatabaseOutline } from './icons/DatabaseOutline.svelte';
export { default as DiscordSolid } from './icons/DiscordSolid.svelte';
export { default as DotsHorizontalOutline } from './icons/DotsHorizontalOutline.svelte';
export { default as EditOutline } from './icons/EditOutline.svelte';
export { default as ExpandOutline } from './icons/ExpandOutline.svelte';
export { default as FileChartBarOutline } from './icons/FileChartBarOutline.svelte';
export { default as GithubSolid } from './icons/GithubSolid.svelte';
export { default as GlobeOutline } from './icons/GlobeOutline.svelte';
export { default as GridPlusOutline } from './icons/GridPlusOutline.svelte';
export { default as InfoCircleOutline } from './icons/InfoCircleOutline.svelte';
export { default as MediumBrand } from './icons/MediumBrand.svelte';
export { default as MoonSolid } from './icons/MoonSolid.svelte';
export { default as SearchOutline } from './icons/SearchOutline.svelte';
export { default as StarOutline } from './icons/StarOutline.svelte';
export { default as Tailwindcss } from './icons/Tailwindcss.svelte';
export { default as ThumbsUpOutline } from './icons/ThumbsUpOutline.svelte';
export { default as TruckFastSolid } from './icons/TruckFastSolid.svelte';
export { default as TwitterSolid } from './icons/TwitterSolid.svelte';
export { default as Visualstudiocode } from './icons/Visualstudiocode.svelte';
export { default as WandMagicSparklesOutline } from './icons/WandMagicSparklesOutline.svelte';
export { default as XSolid } from './icons/XSolid.svelte';